# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
## TEST PUBLISH
platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do
    gradle(
       task: "assemble",
       flavor: "demo",
       build_type: "Release"
     )
  end

desc "Build debug and test APK for screenshots"
lane :build_and_screengrab do
  build_android_app(
    task: 'assemble',
    build_type: 'Debug'
  )
  # build_android_app(
  #   task: 'assemble',
  #   build_type: 'AndroidTest'
  # )
  screengrab()
end

  lane :playstore do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end

  lane :build_aab do
    previous_build_number = google_play_track_version_codes(track: "production")[0]
    current_build_number = previous_build_number + 1

    gradle(
      task: "bundle",  # AAB dosyasını oluşturacak Gradle task'ını belirtin
      build_type: "Release",  # Oluşturulan AAB dosyasının tipini belirtin
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
